# Generated by Django 3.1.8 on 2021-05-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Good"),
                            ("C", "Average"),
                            ("D", "Passing"),
                            ("F", "Failing"),
                        ],
                        max_length=5,
                    ),
                ),
                ("is_final_grade", models.BooleanField()),
            ],
        ),
    ]
