# Generated by Django 3.1.8 on 2021-05-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_lecturer_courses"),
        ("grades", "0003_auto_20210510_1114"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="provided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.lecturer",
            ),
        ),
    ]
