# Generated by Django 3.1.8 on 2021-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20210510_1114'),
        ('courses', '0002_auto_20210510_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='grades',
            field=models.ManyToManyField(blank=True, to='grades.Grade'),
        ),
    ]
