# Generated by Django 3.1.8 on 2021-05-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_auto_20210510_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="courses",
                to="courses.faculty",
            ),
        ),
    ]
