# Generated by Django 3.1.8 on 2021-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_auto_20210510_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
