# Generated by Django 3.1.8 on 2021-05-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_type',
            new_name='course_kind',
        ),
    ]
