# Generated by Django 3.1.8 on 2021-05-17 22:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                (
                    "index_code",
                    models.CharField(
                        blank=True,
                        help_text="Lecturer university's id.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecturer",
                "verbose_name_plural": "Lecturers",
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
